summary9.pdf: summary9.dvi
	dvipdfmx -p a4 summary9.dvi

summary9.dvi: summary9.tex fig1.eps fig2.eps fig3.eps fig4.eps fig5.eps fig6.eps fig7.eps fig8.eps fig9.eps fig10.eps fig11.eps
	platex summary9.tex

fig1.eps: fig1.svgz
	inkscape -z -f fig1.svgz -E fig1.eps
fig2.eps: fig2.svgz
	inkscape -z -f fig2.svgz -E fig2.eps
fig3.eps: fig3.svgz
	inkscape -z -f fig3.svgz -E fig3.eps
fig4.eps: fig4.svgz
	inkscape -z -f fig4.svgz -E fig4.eps
fig5.eps: fig5.svgz
	inkscape -z -f fig5.svgz -E fig5.eps
fig6.eps: fig6.svgz
	inkscape -z -f fig6.svgz -E fig6.eps
fig7.eps: fig7.svgz
	inkscape -z -f fig7.svgz -E fig7.eps
fig8.eps: fig8.svgz
	inkscape -z -f fig8.svgz -E fig8.eps
fig9.eps: fig9.svgz
	inkscape -z -f fig9.svgz -E fig9.eps
fig10.eps: fig10.svgz
	inkscape -z -f fig10.svgz -E fig10.eps
fig11.eps: fig11.svgz
	inkscape -z -f fig11.svgz -E fig11.eps
